fruit_app/profiles/urls.py
from django.urls import path

from fruit_app.profiles.views import create_profile, ProfileDetails, edit_profile, DeleteProfileView

urlpatterns = (
    path("create/", create_profile, name="create_profile"),
    path("details/", ProfileDetails.as_view(), name="profile_details"),
    path("edit/", edit_profile, name="profile_edit"),
    path("delete/", DeleteProfileView.as_view(), name="profile_delete"),

)

fruit_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fruit_app.web.urls')),
    path('fruit/', include('fruit_app.fruits.urls')),
    path('profile/', include('fruit_app.profiles.urls')),
]

fruit_app/fruits/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from fruit_app.fruits import custom_validators
from fruit_app.profiles.models import Profile


# Create your models here.
class Fruit(models.Model):
    MAX_LEN_NAME = 30
    MIN_LEN_NAME = 2

    fruit_name = models.CharField(
        max_length=MAX_LEN_NAME,
        validators=(MinLengthValidator(MIN_LEN_NAME), custom_validators.validate_all_letters,),
        null=False,
        blank=False,
        unique=True,
        verbose_name='Name'
    )
    fruit_image_url = models.URLField(
        null=False,
        blank=False,
        verbose_name='Image URL',
    )
    description = models.TextField(
        null=False,
        blank=False,
    )
    nutrition_info = models.TextField(
        null=True,
        blank=True,
        verbose_name='Nutrition',
    )
    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        blank=True,
        null=False,
    )

fruit_app/profiles/models.py
from django.core.validators import MinLengthValidator
from django.db import models

from fruit_app.fruits import custom_validators


# Create your models here.
class Profile(models.Model):
    MAX_LEN_FN = 25
    MIN_LEN_FN = 2

    MAX_LEN_LN = 35
    MIN_LEN_LN = 1

    MAX_LEN_EMAIL = 40

    MAX_LEN_PASSWORD = 20
    MIN_LEN_PASSWORD = 8

    DEFAULT_AGE = 18

    first_name = models.CharField(
        max_length=MAX_LEN_FN,
        validators=(MinLengthValidator(MIN_LEN_FN), custom_validators.validate_first_letter),
        null=False,
        blank=False,
        verbose_name='First Name'
    )

    last_name = models.CharField(
        max_length=MAX_LEN_LN,
        validators=(MinLengthValidator(MIN_LEN_LN), custom_validators.validate_first_letter),
        null=False,
        blank=False,
        verbose_name='Last Name'
    )

    email = models.EmailField(
        max_length=MAX_LEN_EMAIL,
        null=False,
        blank=False,
    )
    password = models.CharField(
        max_length=MAX_LEN_PASSWORD,
        validators=(MinLengthValidator(MIN_LEN_PASSWORD),),
        null=False,
        blank=False,
        help_text="*Password length requirements: 8 to 20 characters"
    )

    profile_picture = models.URLField(
        null=True,
        blank=True,
        verbose_name='Image URL',
    )

    age = models.PositiveIntegerField(
        null=False,
        blank=True,
        default=DEFAULT_AGE,
    )

fruit_app/profiles/forms.py
from django import forms

from fruit_app.profiles.models import Profile


class CreateProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['first_name', 'last_name', 'email', 'password']

        widgets = {
            'first_name': forms.TextInput(
                attrs={
                    'placeholder': 'First Name'
                }
            ),
            'last_name': forms.TextInput(
                attrs={
                    'placeholder': 'Last Name'
                }
            ),
            'email': forms.EmailInput(
                attrs={
                    'placeholder': 'Email'
                }
            ),
            'password': forms.PasswordInput(
                attrs={
                    'placeholder': 'Password'
                }
            ),
        }

        labels = {
            'first_name': '',
            'last_name': '',
            'email': '',
            'password': '',
        }

fruit_app/profiles/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from fruit_app.profiles.forms import CreateProfileForm
from fruit_app.profiles.models import Profile
from fruit_app.web.views import get_profile
from django.views import generic as views


# Create your views here.
def create_profile(request):
    profile = get_profile()
    form = CreateProfileForm(request.POST or None)
    if request.method == "POST":

        if form.is_valid():
            form.save()
            return redirect("dashboard")

    context = {
        "profile": profile,
        "form": form,
    }
    return render(request, "profiles/create-profile.html", context)


class ProfileDetails(views.DetailView):
    template_name = "profiles/details-profile.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        return get_profile()


def edit_profile(request):
    profile = Profile.objects.first()
    if request.method == 'GET':
        form = ProfileEditForm(instance=profile)
    else:
        form = ProfileEditForm(request.POST, instance=profile)
        if form.is_valid():
            form.save()
            return redirect('profile_details')
    context = {
        'profile': profile,
        'form': form
    }
    return render(request, 'profiles/edit-profile.html', context)

    def get_success_url(self):
        return reverse('dashboard', kwargs={'pk': self.object.pk, })

    def get_form(self, form_class=None):
        form = super().get_form(form_class=form_class)

        form.fields['first_name'].label = 'First Name:'
        form.fields['last_name'].label = 'Last Name:'
        form.fields['profile_picture'].label = 'Image URL:'
        form.fields['age'].label = 'Age:'

        return form

class DeleteProfileView(views.DeleteView):
    template_name = "profiles/delete-profile.html"
    success_url = reverse_lazy("index")

    def get_object(self, queryset=None):
        return get_profile()

templates/profiles/create-profile.html
{% extends "base.html" %}
{% block main_content %}
    <!-- Create Profile Form -->
    <section id="register">
        <div class="form">
            <h2>Create Profile</h2>
            <form action="{% url "create_profile" %}" method="post">
                {{ form }}

                <button type="submit">Create</button>
                {% csrf_token %}
            </form>
        </div>
    </section>
    </main>
    </div>
{% endblock %}

templates/profiles/delete-profile.html
{% extends "base.html" %}
{% block main_content %}

        <section id="edit">

            <div class="form">
                <h1>Are you sure you want to delete your profile?</h1>

                <form action="{% url "profile_delete" %}" method="post" id='delete' class="register-form">
                    {{ form.as_p }}
                    <button type="submit">Yes</button>

                    {% csrf_token %}

                </form>

            </div>
            
        </section>
    </main>
</div>

{% endblock %}

templates/profiles/details-profile.html
{% extends "base.html" %}
{% load static %}
{% block main_content %}

    <section id="details">
        <div id="details-wrapper">
            <h2>Profile Details</h2>
            {% if object.profile_picture %}
                <img id="details-img" src="{{ object.profile_picture }}"
                     alt="profile img"/>
            {% else %}

                <img id="details-img" src="{% static "/images/default.jpg" %}" alt="profile img"/>
            {% endif %}

            <p id="details-title">{{ object.first_name|add:" "|add:object.last_name }}</p>

            <div id="info-wrapper">
                <div id="details-description">

                    <p>
                        {{ object.email }}
                    </p>

                    <p>
                        Age: 18
                    </p>

                    <p id="nutrition">Posts: {{ object.fruit_set.count }}</p>

                </div>

                <div id="action-buttons">
                    <a href="{% url "profile_edit" %}" id="edit-btn">Edit</a>
                    <a href="{% url "profile_delete" %}" id="delete-btn">Delete</a>
                </div>
            </div>
        </div>
    </section>

    </main>
    </div>
{% endblock %}

templates/profiles/edit-profile.html
{% extends "base.html" %}
{% block main_content %}

        <!-- Edit Profile Form -->

        <section id="register">
            <div class="form">
                <h2>Edit Profile</h2>
                <form action="{% url "profile_edit" %}"  method="post">
                    {{ form.as_p }}
                    <button type="submit">Edit</button>
                    {% csrf_token %}

                </form>
            </div>
        </section>

    </main>
</div>
<!-- footer -->
{% endblock %}